### ISSUE TITLE
keycloak persistent DB

### ISSUE THREAD

**Issue by danseo-reisys** [codecentric/helm-charts#118]
Hi,
trying to use keycloak with persistent db option on openshift. 

helm install --name keycloak2 codecentric/keycloak --set keycloak.persistence.deployPostgres=true

it creates postgres however, i don't see the postgres on persistent volume.

how can this be fixed?

**Comment by unguiculus** [comment]
Please provide more details. Otherwise I won't be able to help.

**Comment by kcao3** [comment]
helm3 upgrade  --install keycloak --namespace keycloak-test \
  --set keycloak.replicas=2 \
  --set keycloak.persistence.deployPostgres=true \
  --set keycloak.persistence.dbVendor=postgres \
  --set keycloak.ingress.enabled=true .

kubectl -n keycloak-test get pod
NAME                           READY   STATUS    RESTARTS   AGE
keycloak-0                    1/1        Running    0               8m
keycloak-1                    1/1        Running    0               8m
keycloak-postgresql-0   1/1       Running     0              8m
[kcao@radcloud3 keycloak]$ kubectl -n keycloak-test get pvc
No resources found in keycloak-test namespace.

When the keycloak-postgresql-0 pod is cycled, since keycloak-postgresql does not have a persistent volume, although kubernetes is able to launch a new keycloak-postgresql-0 pod, all data was LOST. 

What other information is needed in this case?

**Comment by kcao3** [comment]
When adding this flag to the helm cmd:  --set postgresql.persistence.enabled=true, a persistent volume will be created for each postgres instance. 

This issue should be closed now.
