### ISSUE TITLE
Custom startup scripts not executed before Keycloak startup

### ISSUE THREAD

**Issue by method350** [codecentric/helm-charts#136]
Custom script defined in values.yaml 

`  ## Custom script that is run before Keycloak is started. `
`  startupScripts: `
`     mystartup.sh: `

is created in /opt/jboss/startup-scripts folder, but not executed.

Chart version 6.0.0

**Comment by unguiculus** [comment]
The test for the chart configures a startup script which is indeed run. You can see this in the test logs, e. g.: https://circleci.com/gh/codecentric/helm-charts/800?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

Please share your configuration. Otherwise it's hard to provide assistence.

**Comment by unguiculus** [comment]
Closing this now. Feel free to create a new issue if the problem persists.
