### ISSUE TITLE
cannot access keycloak with args like -Dkeycloak.profile.feature.upload_scripts

### ISSUE THREAD

**Issue by y0zg** [codecentric/helm-charts#279]
chart version: `9.0.1`                  
app version: `11.0.0`
Details https://github.com/gabibbo97/charts/issues/33#issuecomment-671376045

Any options to add args like below doesn't allow me to access keycloak via http and port-forward anymore

Pods and sts are in good condition, logs are good as well and I see in logs argument upload_scripts is passed
```
args: 
- -Dkeycloak.profile.feature.upload_scripts=enabled
```

Please let me know the proper way to fix this

**Comment by unguiculus** [comment]
The Keycloak Docker image set the following args:
https://github.com/keycloak/keycloak-containers/blob/master/server/Dockerfile#L32

If you override args you need to make sure to copy these as well. The chart does not make any assumptions as to what is set by the image because it needs to work with any custom image as well. This is something that has explicitly been changed in release 9.0.0 (see https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/README.md#from-chart-versions--900).
