### ISSUE TITLE
unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1"

### ISSUE THREAD

**Issue by barnybadzoo** [codecentric/helm-charts#349]
Hi after the last commit i receive this error message if i want to install per helm:

unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1"

I try to install on k3OS v0.19.2-dev.4 .
My Versions:

Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"**v1.18.6+k3s1**", GitCommit:"6f56fa1d68a5a48b8b6fdefa8eb7ead2015a4b3a", GitTreeState:"clean", BuildDate:"2020-07-16T20:46:15Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}

Till yesterday everything worked fine..

**Comment by barnybadzoo** [comment]
Workaround: Install an older Version with the Versionflag:

> sudo helm install keycloak codecentric/keycloak --version "9.5.0" --namespace keycloak --values ./keycloak-values.yaml

**Comment by jonkerj** [comment]
I am facing the same issue. The code in `_helpers.tpl` assumes that if `networking.k8s.io/v1` is present, `Ingress` lives there. In my cluster (1.18.10) this is not the case: `Ingress` is still `v1beta1`. I am not a helm templating wizard (otherwise I'd PR it), but it seems to me that it could be better to check the Kubernetes version instead. 

This change was introduced in #334.

**Comment by Flowkap** [comment]
@jonkerj is correct. The condition is false. In 1.18 the api version exists but INgress is not yet in it. So this helm version is broken for K8s 1.18.x

**Comment by seboudry** [comment]
Hi! Also have this issue with K8S 1.17 BTW

**Comment by 0xErnie** [comment]
As far as I understood the cause of the problem is, that only the existence of the API is checked, but not the existence of the class Ingress, so the following might solve the problem:
﻿`.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress"`
istead of
`.Capabilities.APIVersions.Has "networking.k8s.io/v1"`

**Comment by jildertmiedema** [comment]
Solved with https://github.com/codecentric/helm-charts/pull/357

**Comment by unguiculus** [comment]
Thanks @jildertmiedema
