### ISSUE TITLE
[Keycloak] Update Keycloak version to 13.0.1

### ISSUE THREAD

**Issue by thomasdarimont** [codecentric/helm-charts#430]

**Comment by christopheblin** [comment]
for information,  I already used 12.0.1 and tried to update to 13.0.1 through a classical `helm upgrade`

there is an issue in clustering mode : when a 13.0.1 pod joins the cluster, he does not understand the messages sent by a 12.0.1

```
07:59:47,331 ERROR [org.infinispan.CLUSTER] (thread-5,null,keycloak-2) ISPN000474: Error processing request 16@keycloak-1: protostream.com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
```

I do not know if this should be supported by keycloak or not

to "fix" this error, we did `helm upgrade && kubectl delete pod keycloak-0 keycloak-1 keycloak-2` so that all replicas are started in the same version

**however, be warned that all sessions (and refresh tokens) are lost in this case**

this may be a problem if your client apps are not able to deal with the reject of a refresh token
