### ISSUE TITLE
[Q&A] Internally calling the service

### ISSUE THREAD

**Issue by shyam-ks** [codecentric/helm-charts#645]
If I am calling Keycloak service internally (within the cluster) from another pod, should I use headless service or the cluster IP service ?
Thanks in advance

**Comment by grieshaber** [comment]
Hey @shyam-ks,

for those kind of calls you should use the "normal" cluster ip service. This service assures the "Loadbalancing" / proxy part of the service concept is used.
The headless service is in place in order to allow certain components to get all pod ips directly instead of the ip adress of a proxy-service.
