### ISSUE TITLE
Question/Imporvement. KeycloakX. PostgreSQL dependency chart

### ISSUE THREAD

**Issue by AndreiPaulau** [codecentric/helm-charts#646]
Hello Gent's,

Could you please shed some light on removing PostgreSQL dependency chart while moving to KeycloakX?

In addition to `database:` section I'd propose to use something like:

```# External PostgreSQL configuration.
# To use an external PostgreSQL instead of the automatically deployed postgresql chart:
# 1. set postgresql.enabled to false
# 2. uncomment and configure the externalPostgreSQL connection URL (e.g. postgresql://user:pass@host:5432/database)
externalPostgreSQL:
# Read external PostgreSQL configuration from a secret.
# This should point at a secret file with a single key which specifyies the connection string.
# Overrides any other PostgreSQL related values
externalPostgreSQLSecret: {}
  # name: postgres
  # key: connectionString
```
as of `db-url`

Many thanks!

**Comment by grieshaber** [comment]
Hey @AndreiPaulau, 
unfortunately no, i cannot provide any insights regarding that postgresql topic. 
There's been a switch on the maintainers of these charts and i'm lacking the "historical decisions" etc.

Regarding your proposed changes - i don't quite get, why one would want to use the "externalPostgresSQL" string instead of the values provided via the `database:` block.
