### ISSUE TITLE
keycloak doesn't use postgres on openshift

### ISSUE THREAD

**Issue by Epic55** [codecentric/helm-charts#650]
hi, keycloak doesn't use postgresql db on openshift. I passed all necessary environment variables for postgres to keycloak pod to use postgre. In kubernetes everything works fine, keycloak uses postgres, but when i launch the same configuration in openshift, it doesn't work, keycloak writes in logs that it is using postgres db, but later in log it writes it uses internal h2 db. What is the problem?

**Comment by Docteur-RS** [comment]
I have the same pb but on classic Kubernetes.

I have this line in the logs
```
09:35:22,960 INFO  [org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory] (ServerService Thread Pool -- 57) Database info: {databaseUrl=jdbc:h2:/opt/jboss/keycloak/standalone/data/keycloak, databaseUser=SA, databaseProduct=H2 1.4.197 (2018-03-18), databaseDriver=H2 JDBC Driver 1.4.197 (2018-03-18)}
```

New users are not added to the postgres DB...

**Comment by Docteur-RS** [comment]
Seems we fixed the pb.
We upgraded to 18.0.4 first.
We still had 2 problems.

The first one was that the postgres wasn't detected and the H2 was always used instead. We had `command: ["/bin/sh"]` switched to `command: []`. It finaly did write to the correct DB. We tested so many things that I'm not sure this was the fix but it's possible. It might have override the default entrypoint in the dockerfile in charge of detecting the postgres...

The second one was the reset of the DB content. It was because of the arg `-Dkeycloak.migration.strategy=OVERWRITE_EXISTING` which was overwriting the content of the DB. We switch to "IGNORE_EXISTING" and now it's good.
