### ISSUE TITLE
[keycloak] WildFly distribution is removed

### ISSUE THREAD

**Issue by Footur** [codecentric/helm-charts#666]
With the release of Keycloak v20.0.0 WildFly is no longer [supported](https://www.keycloak.org/docs/latest/release_notes/index.html#wildfly-distribution-removed). Is it time to delete the helm chart of Keycloak WildFly edition?

**Comment by Footur** [comment]
bump

**Comment by marknelissen** [comment]
Before removing, it would be good to have clear migration instructions for people coming from the old charts. I am probably not the only one stuck on the wildfly chart because I have no idea how to migrate to the new chart without starting a new environment from scratch. Which for production is a no go.

**Comment by Footur** [comment]
bump
