### ISSUE TITLE
[keycloak] HPA API Version is Deprecated in K8s 1.26

### ISSUE THREAD

**Issue by rgarcia6520** [codecentric/helm-charts#715]
The API version `v2beta2` for the HPA resource is deprecated in k8s version 1.26 https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-26 

Should be updated to `v2`

**Comment by geNAZt** [comment]
We also ran into that issue lately trying to recover a keycloak installation. It was noted that autoscaling uses this old CRD on a 1.26.5 GKE.

**Comment by LarsBingBong** [comment]
Use e.g. something like ytt to do some overlaying of the generated Helm template YAML. See: https://carvel.dev/ytt/docs/v0.44.0/#patching-aka-overlaying

In that way you would be able to overwrite the generated YAML so that you, on the fly, can change the API version to one that's compatible with the version in the cluster.

For an example see: https://github.com/carvel-dev/ytt/blob/develop/examples/k8s-overlay-ingress/network-api-fix.yaml

**Comment by LarsBingBong** [comment]
Thank you @rgarcia6520. However, isn't this chart in general getting deprecated in favor of Keycloak running on Quarkus?
